# CONFIG SETUP
alluka_explain_config: "alluka_zoldyck"   #Change me from "alluka_zoldyck"

bot_token: "1276328038:AAFGaVUWKC1UWB4e9kuM3LMde8NlgmZdR3Q"  
owner_id: 992712818
api_key: 1570274
api_hash: 'd463fbcaa44274b3e969028dd570d3ab'
owner_username: "OtakuHarsh"
database_url: "postgres://dztjlbbs:Huml9xKozjXld1qrG3fGWEJMGadcdeSA@lallah.db.elephantsql.com:5432/dztjlbbs"
message_dump: "https://t.me/joinchat/OyuYchSZY4V4PDorzyDgjA"
gban_dump: "https://t.me/joinchat/OyuYchsX9rwlQDWyuCcHmA"
load: []
no_load: []
cert_path: None
port: 5000
workers: 4
webhook: False
url: None
allow_excl: False
del_cmds: False
strict_gban: True
strict_gmute: True
spammers_lists: [100]
ban_sticker: 'CAACAgUAAxkBAAIHsl5nbqXdDTmpG2HFDNhnwvE5kFbWAAI9AQAC3pTNLzeTCUmnhTneGAQ'


# API SETUP
cash_api: 810d07cf11d835988d35  
time_api: None  
wall_api: 4714b015a2eb31fab8d3b1849d93574d
lydia_api: 'b98eb410a16401c68d4d15a81b25092c483026b95ec9cba24c03a046d0066f6e03f9770566543b05122ecbf86516ed8c1ee1be1bc067078ad32f0626da54e417'
sw_api: 'VxZMFkViTz6vLAzToVAYeK5J7Bx3EGL20z2_GbGLDy3Aa3NLfFmO7wMcfKHKMGSY'

# Zoldyck family config
alluka: [936828744]
hisoka: [680240877]
ging: [239508098]
shizuku: [516449930]
silva: [331863490]
gon: [123456789] 
illumi: [854853029]
leorio: [575737330]
biscuit: [586760757]
chrollo: [806845434]
killua: [165822682] 
meruem: [696086626] 
kite: [604968079] 

# Permission
dev_users: [637215887]
sudo_users: []
support_users: []
whitelist_users: []
